image: maven:3.6.1-jdk-11 

stages:
    - build
    - test
    - deploy

build : 
    stage : build
    before_script:
        - . setup-mvn-proxy.sh
    script :
        - cd users && mvn clean

test : 
    stage : test
    before_script:
        - . setup-mvn-proxy.sh
    script :
        - cd users && mvn test 



deploy : 
    stage : deploy
    only : 
      - master
    before_script:
        - . setup-mvn-proxy.sh && echo "$CI_SSH_KEY" > ci_private_key.pem && chmod 400 ci_private_key.pem
    script :
        - cd users && mvn package 
        - scp -v -o StrictHostKeyChecking=no -i ../ci_private_key.pem /builds/p1809163/mif13-2021/target/users.war gitlabci@192.168.75.22:/opt/tomcat/webapps/v1.war
