image: node:latest
stages: 
    - deploy
    - lint

deploy:
    stage: build
    only:
        - tp3
    before_script:
        - cd api
        - npm i
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    script:
        - eval $(ssh-agent -s)
        - echo "$CI_SSH_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - ssh gitlabci@192.168.75.22 "rm -fr dist/*"
        - scp -r dist gitlabci@192.168.75.22:~
        - ssh gitlabci@192.168.75.22 "cd /var/www/api; rm -r *; cp -r ~/dist/* ./"
