image: maven:3.6.1-jdk-11 

stages:
    - build
    - test
    - deploy

build : 
    stage : build
    before_script:
        - . setup-mvn-proxy.sh
    script :
        - mvn compile

test : 
    stage : test
    before_script:
        - . setup-mvn-proxy.sh
    script :
        - mvn test 



deploy : 
    stage : deploy
    only : 
      - master
    before_script:
        - . setup-mvn-proxy.sh && echo "$CI_SSH_KEY" > ci_private_key.pem && chmod 400 ci_private_key.pem
    script :
        - mvn package 
        
